name: Deploy to Amazon ECS (NonProd)

on: workflow_dispatch

env:
  ECS_CLUSTER: geekway-nonprod

permissions:
  contents: read

jobs:
  deploy-librarians:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ecr-repository: frontends-librarian
      ecs-service: frontends-librarian
      ecs-task-definition: librarian/.aws/taskdefinition-nonprod.json
      container-name: frontends-librarian
      ecs-cluster: ${{ env.ECS_CLUSTER }}
    secrets: inherit
  deploy-admin:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ecr-repository: frontends-admin
      ecs-service: frontends-admin
      ecs-task-definition: board-game-admin/.aws/taskdefinition-nonprod.json
      container-name: frontends-admin
      ecs-cluster: ${{ env.ECS_CLUSTER }}
    secrets: inherit
  deploy-play-and-win:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ecr-repository: frontends-play-and-win
      ecs-service: frontends-play-and-win
      ecs-task-definition: play-prize-entry/.aws/taskdefinition-nonprod.json
      container-name: frontends-play-and-win
      ecs-cluster: ${{ env.ECS_CLUSTER }}
    secrets: inherit
