name: Deploy to Amazon ECS (NonProd)

on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy-librarian:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ecr-repository: frontends-librarian
      ecs-service: frontends-librarian
      ecs-task-definition: librarian/.aws/taskdefinition-nonprod.json
      container-name: frontends-librarian
      ecs-cluster: geekway-nonprod
      folder-name: librarian
      always-override-limit: false
      api-identifier: ${{ github.repository.secrets.API_IDENTIFIER }}
      api-url: ${{ github.repository.secrets.API_URL }}
      auth-callback: ${{ github.repository.secrets.AUTH_CALLBACK_LIBRARIAN }}
      auth-client-id: ${{ github.repository.secrets.AUTH_CLIENT_ID }}
      logout-return-url: ${{ github.repository.secrets.LOGOUT_RETURN_URL_LIBRARIAN }}
      auth-domain: ${{ github.repository.secrets.AUTH_DOMAIN }}
      webpack-mode: ${{ github.repository.secrets.WEBPACK_MODE }}
    secrets: inherit
  deploy-admin:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ecr-repository: frontends-admin
      ecs-service: frontends-admin
      ecs-task-definition: board-game-admin/.aws/taskdefinition-nonprod.json
      container-name: frontends-admin
      ecs-cluster: geekway-nonprod
      folder-name: board-game-admin
      always-override-limit: false
      api-identifier: ${{ github.repository.secrets.API_IDENTIFIER }}
      api-url: ${{ github.repository.secrets.API_URL }}
      auth-callback: ${{ github.repository.secrets.AUTH_CALLBACK_ADMIN }}
      auth-client-id: ${{ github.repository.secrets.AUTH_CLIENT_ID }}
      logout-return-url: ${{ github.repository.secrets.LOGOUT_RETURN_URL_ADMIN }}
      auth-domain: ${{ github.repository.secrets.AUTH_DOMAIN }}
      webpack-mode: ${{ github.repository.secrets.WEBPACK_MODE }}
    secrets: inherit
  deploy-play-and-win:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ecr-repository: frontends-play-and-win
      ecs-service: frontends-play-and-win
      ecs-task-definition: play-prize-entry/.aws/taskdefinition-nonprod.json
      container-name: frontends-play-and-win
      ecs-cluster: geekway-nonprod
      folder-name: play-prize-entry
      always-override-limit: false
      api-identifier: ${{ github.repository.secrets.API_IDENTIFIER }}
      api-url: ${{ github.repository.secrets.API_URL }}
      auth-callback: ${{ github.repository.secrets.AUTH_CALLBACK_PLAYANDWIN }}
      auth-client-id: ${{ github.repository.secrets.AUTH_CLIENT_ID }}
      auth-domain: ${{ github.repository.secrets.AUTH_DOMAIN }}
      webpack-mode: ${{ github.repository.secrets.WEBPACK_MODE }}
      logout-return-url: NA
    secrets: inherit
